### ISSUE TITLE
.gif URL from Discord isn't showing

### ISSUE THREAD

**Issue by DARG367** [Domin-MND/profile-card#6]
![image](https://github.com/domin-mnd/profile-card/assets/45442449/ad80acc9-1fa9-45d4-9bdd-9efc8f5eea65)

I tried also uploading to other sites but when inspecting the source it's showing an .avif file instead of the .gif file.

**Comment by dominnya** [comment]
Sorry for late answer as I've been on vacation, I will look into it in the next few days

**Comment by dominnya** [comment]
Had a quick look at the issue and it seems like it's related to https://github.com/withastro/astro/issues/5028

Fixed it and tested it with both gif & png just in case. Banners now convert to optimized webp format. May look into further improvement of image loading later. Thanks for the contribution.

Fixed in https://github.com/domin-mnd/profile-card/commit/359f2d39b1a32dadc7ecd7bb8eaa790412ea74ea
